[project]
name = "crm-backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "advanced-alchemy>=1.11.0",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "httpx>=0.28.1",
    "litestar[standard]>=2.24.0",
    "python-dotenv>=1.2.4",
]

[dependency-groups]
dev = [
    "ruff>=0.16.10",
]
